#Der Prefix vor Commands
Prefix: '&8[&6Lobby&8-&cRel&8]'
Items:
  Navigator:
    Enabled: true
    Slot: 0
  PlayerHider:
    Enabled: true
    Slot: 1
  Settings:
    Enabled: true
    Slot: 8
  Switcher:
    Enabled: true
    Slot: 7
  Swticher:
    Enabled: true
Scoreboard:
  Enabled: false
Language:
  Folder: plugins/Lobby-Rel/Lang/
  Default: en_US
LoadingHotbar:
  Enabled: true
  LoadingTime: 5
Updater:
  Enabled: true
  UpdateOnStart: false
  InformAdmin: true
Storage:
  Type: json
  FilePath: plugins\Lobby-Rel\players
PluginSuport:
  UltraCosmetics:
    Enabled: true
  BetterNick:
    Enabled: true
  ProtocolLib:
    Enabled: true
  Vault:
    Enabled: true
LobbySwitcher:
  UpdateTime: 100
  Groups:
  - SERVER;PremiumLobby
  - STARSTWITH;Lobby
  - CLOUDNET;aCloudnetGroup
CheckForIdeods:
  CloudNet-Lobby: true
maxLife: 6
maxFood: 20
PlayerSettings:
  Default:
    Navigator: 0
    PlayerHider: 1
Animation:
  Teleport: true
  DoubleJump: true
Gui:
  Navigator:
    Size: 5
    Position:
      Item-0:
        X: 4
        Y: 0
        enabled: true
      Item-1:
        X: 2
        Y: 1
        enabled: true
      Item-2:
        X: 2
        Y: 3
        enabled: true
      Item-3:
        X: 4
        Y: 4
        enabled: true
      Item-4:
        X: 6
        Y: 3
        enabled: true
      Item-5:
        X: 6
        Y: 1
        enabled: true


