main: de.phyrone.lobbyrel.LobbyPlugin
name: Lobby-Rel
version: ${project.version}
softdepend: [SmartInvs,EffectLib,PlaceholderAPI,QuickBoard,ProtocolLib,BetterNick,UltraCosmetics]
author: Phyrone
debug: false
commands:
     lobby:
          aliases: [lb,lobbysystem,lobby-rel,lobby-reloaded]
     build:
     spawn:
     setwarp:
     setspawn: