main: de.phyrone.lobbyrel.LobbyPlugin
name: Lobby-Rel
version: ${project.version}
softdepend: [SmartInvs,EffectLib,PlaceholderAPI,QuickBoard,ProtocolLib]
author: Phyrone
commands:
     lobby:
          aliases: [lb,ls,lobbysystem,lobby-rel,lobby-reloaded]
     build:
     spawn:
     setwarp:
     setspawn: