main: de.phyrone.lobbyrel.LobbyPlugin
name: Lobby-Rel
version: 0.3.06-ALPHA
softdepend: [SmartInvs,EffectLib,PlaceholderAPI,QuickBoard]
author: Phyrone
commands:
     lobby:
          aliases: [lb,ls,lobbysystem,lobby-rel,lobby-reloaded]
     build:
     spawn:
     setwarp:
     setspawn: